import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { generateWithGroq } from '@/lib/groq'

export async function POST(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { stage } = await request.json()

    const job = await prisma.job.findUnique({ where: { id: params.id } })
    if (!job) return NextResponse.json({ error: 'Job not found' }, { status: 404 })

    const sources = await prisma.source.findMany({
      where: { jobId: params.id, reliabilityTier: 'peer_reviewed' },
      orderBy: { createdAt: 'asc' },
      take: 15,
    })

    const top3 = await prisma.top3Ideas.findUnique({ where: { jobId: params.id } })
    const ideas = top3 ? JSON.parse(top3.ideasJson) : []

    const candidates = await prisma.candidateTopic.findMany({
      where: { jobId: params.id, status: { in: ['selected', 'active'] } },
      orderBy: { score: 'desc' },
      take: 10,
    })

    const peerSources = sources
      .map((s) => `• ${s.title}${s.venue ? ` (${s.venue})` : ''}${s.snippet ? `\n  ${s.snippet.slice(0, 150)}...` : ''}`)
      .join('\n')

    const topicContext = candidates.map((c) => c.label).join(', ')

    if (stage === 'context') {
      // Return the ARS-formatted context package for export / clipboard
      const arsContext = buildARSContext(job.topicQuery, ideas, topicContext, peerSources)
      return NextResponse.json({ arsContext })
    }

    if (stage === 'outline') {
      const primaryIdea = ideas[0]
      const prompt = `You are an academic paper planner. Generate a detailed IMRaD-style paper outline for the following research idea.

RESEARCH TOPIC: ${job.topicQuery}
PRIMARY RESEARCH IDEA: ${primaryIdea ? primaryIdea.title : job.topicQuery}
PROBLEM: ${primaryIdea ? primaryIdea.problem_to_solve : ''}
METHODS: ${primaryIdea ? primaryIdea.proposed_method.join('; ') : ''}

KEY LITERATURE:
${peerSources}

Generate a paper outline with:
- Title (compelling academic title)
- Abstract (3-sentence structure: background, gap, contribution)
- Introduction sections (3-4 subsections with key points for each)
- Methods sections (3-4 subsections)
- Results/Expected Findings sections (3-4 subsections)
- Discussion sections (2-3 subsections including limitations)
- Conclusion (1-2 sentences)
- Key References (list 5 from the literature above)

RESPOND AS JSON:
{
  "title": "...",
  "abstract": "...",
  "sections": [
    { "name": "Introduction", "subsections": [{ "heading": "...", "keyPoints": ["...", "..."] }] },
    { "name": "Methods", "subsections": [...] },
    { "name": "Results", "subsections": [...] },
    { "name": "Discussion", "subsections": [...] },
    { "name": "Conclusion", "subsections": [{ "heading": "Conclusion", "keyPoints": ["..."] }] }
  ],
  "keyReferences": ["...", "..."]
}`

      const outline = await generateWithGroq(prompt)
      return NextResponse.json({ outline })
    }

    return NextResponse.json({ error: 'Unknown stage' }, { status: 400 })
  } catch (error) {
    console.error('Paper pipeline error:', error)
    return NextResponse.json({ error: 'Pipeline failed' }, { status: 500 })
  }
}

function buildARSContext(
  topicQuery: string,
  ideas: any[],
  topics: string,
  sources: string
): string {
  const primaryIdea = ideas[0]

  return `# Hypothesis Atlas Research Export — ARS Context Package

## Research Topic
${topicQuery}

## Primary Research Idea
**Title:** ${primaryIdea?.title ?? topicQuery}

**Problem to Solve:**
${primaryIdea?.problem_to_solve ?? 'See research topic above.'}

**Proposed Method:**
${primaryIdea?.proposed_method?.map((m: string) => `- ${m}`).join('\n') ?? ''}

**Next Steps:**
${primaryIdea?.next_3_steps?.map((s: string) => `- ${s}`).join('\n') ?? ''}

## Key Research Topics
${topics}

## Key Literature (Peer-Reviewed)
${sources}

---

## How to use with ARS (Academic Research Skills for Claude Code)

1. Open Claude Code in your terminal
2. Run: \`/ars-plan\`
3. When the Socratic mentor asks about your paper, paste the content above as context
4. Or run: \`/ars-full\` for the complete pipeline (research → write → review → revise → finalize)

**Tip:** Run \`/ars-outline\` first for a quick detailed outline + evidence map without the full draft.

---
Generated by Hypothesis Atlas · ${new Date().toISOString()}
`
}
